In [ ]:
import numpy as np

In [ ]:
# %timeit [i+1 for i in range(900000000)]

In [ ]:
# %timeit np.arange(900000000)+1

2.64 ms ± 42.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
n=np.array([1,2,3,4])
n

array([1, 2, 3, 4])

In [ ]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
type(b)

numpy.ndarray

In [ ]:
l=[1,2,3,4]
p=np.array(l)
p

array([1, 2, 3, 4])

In [ ]:
k=np.linspace(1,10,4)
print(k)

[ 1.  4.  7. 10.]


In [ ]:
y=np.loadtxt("file.txt",delimiter="and")
print(y)

[1. 2. 3.]


In [ ]:
s=np.empty((3,3))
s

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.51377261e-321],
       [1.05699242e-307, 8.01097888e-307, 2.80103444e-312]])

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [ ]:
print (a[0])
print (a[4])

1
5


In [ ]:
a[[0,4]]

array([1, 5])

In [ ]:
a
a=[1,2,3,4,5,6]

In [ ]:
b=[]
for i in a:
    if(i%2!=0):
        b.append(0)
    else:
        b.append(i)
print (b)    

[0, 2, 0, 4, 0, 6]


In [ ]:
# k=a%2==0
# k
# print (a[k])

a[a%2!=0]=0
print (a)


# b=a%2==0
# a[a%2!=0]=0
# print(b)
# print(a[b])
# print(a)

[0 2 0 4 0 6]


In [ ]:
a=np.array([1,2,3,10,5,6],np.int8)
print(a)

[ 1  2  3 10  5  6]


In [ ]:
a.shape

(6,)

In [ ]:
a.ndim

1

In [ ]:
a.dtype

dtype('int8')

In [ ]:
a.size

6

In [ ]:
a.nbytes

6

In [ ]:
a.argmax()

3

In [ ]:
a.argmin()

0

In [ ]:
a.argsort()

array([0, 1, 2, 4, 5, 3], dtype=int64)